"""LangGraph adapter for AgentKit apps."""

from __future__ import annotations

from collections.abc import AsyncGenerator, Iterable
import hashlib
import inspect
import json
from dataclasses import dataclass
from typing import Any

try:
    from langchain_core.messages import HumanMessage
except ImportError as exc:  # pragma: no cover - depends on optional packages.
    raise ImportError(
        "LangGraph bridge requires langgraph/langchain-core. "
        "Install langgraph or use the requirements generated by agentkit migrate."
    ) from exc

from google.adk.agents.base_agent import BaseAgent
from google.adk.agents.invocation_context import InvocationContext
from google.adk.events import Event, EventActions
from google.genai import types
from pydantic import PrivateAttr

try:
    from langgraph.types import Command
except ImportError:  # pragma: no cover - older optional langgraph versions.
    Command = None  # type: ignore[assignment]

from agentkit.frameworks._common import (
    UnsupportedFrameworkAgentError,
    adk_event,
    chunk_delta,
    chunk_to_text,
    user_text,
)


LANGGRAPH_PENDING_INTERRUPT_STATE_KEY = "agentkit:langgraph:pending_interrupt"
_OUTPUT_FIELD_KEYS = ("answer", "output", "final", "response", "text", "messages")


@dataclass(frozen=True)
class _FactoryCall:
    args: tuple[Any, ...]
    kwargs: dict[str, Any]


def _method_kwargs(method: Any, kwargs: dict[str, Any]) -> dict[str, Any]:
    try:
        signature = inspect.signature(method)
    except (TypeError, ValueError):
        return kwargs

    parameters = signature.parameters
    accepts_kwargs = any(param.kind == inspect.Parameter.VAR_KEYWORD for param in parameters.values())
    return {key: value for key, value in kwargs.items() if accepts_kwargs or key in parameters}


def _factory_call(factory: Any, config: dict[str, Any] | None) -> _FactoryCall:
    if not callable(factory):
        raise UnsupportedFrameworkAgentError(
            "LangGraph graph_factory=True requires a callable entry that "
            "returns a compiled graph-like object."
        )

    try:
        signature = inspect.signature(factory)
    except (TypeError, ValueError):
        return _FactoryCall(args=(config,), kwargs={})

    parameters = list(signature.parameters.values())
    required = [
        param
        for param in parameters
        if param.default is inspect.Parameter.empty
        and param.kind
        in {
            inspect.Parameter.POSITIONAL_ONLY,
            inspect.Parameter.POSITIONAL_OR_KEYWORD,
            inspect.Parameter.KEYWORD_ONLY,
        }
    ]
    if len(required) > 1:
        names = ", ".join(param.name for param in required)
        raise UnsupportedFrameworkAgentError(
            "LangGraph Server graph factory entries may require at most one "
            f"RunnableConfig argument; required parameters found: {names}."
        )

    if any(param.kind == inspect.Parameter.VAR_POSITIONAL for param in parameters):
        return _FactoryCall(args=(config,), kwargs={})

    if required:
        param = required[0]
        if param.kind == inspect.Parameter.KEYWORD_ONLY:
            return _FactoryCall(args=(), kwargs={param.name: config})
        return _FactoryCall(args=(config,), kwargs={})

    optional_config = next(
        (
            param
            for param in parameters
            if param.name in {"config", "runnable_config"}
            and param.kind
            in {
                inspect.Parameter.POSITIONAL_OR_KEYWORD,
                inspect.Parameter.KEYWORD_ONLY,
            }
        ),
        None,
    )
    if optional_config is None:
        return _FactoryCall(args=(), kwargs={})
    if optional_config.kind == inspect.Parameter.KEYWORD_ONLY:
        return _FactoryCall(args=(), kwargs={optional_config.name: config})
    return _FactoryCall(args=(config,), kwargs={})


def _jsonable(value: Any) -> Any:
    try:
        json.dumps(value, ensure_ascii=False)
        return value
    except Exception:
        return str(value)


def _interrupt_payload(data: Any) -> Any | None:
    if not isinstance(data, dict) or "__interrupt__" not in data:
        return None
    interrupts = data.get("__interrupt__")
    if not isinstance(interrupts, (list, tuple)) or not interrupts:
        return interrupts
    values: list[dict[str, Any]] = []
    for interrupt in interrupts:
        values.append(
            {
                "id": getattr(interrupt, "id", None),
                "value": _jsonable(getattr(interrupt, "value", interrupt)),
            }
        )
    return values


def _resume_value(text_input: str) -> Any:
    stripped = text_input.strip()
    if stripped.startswith(("{", "[")):
        try:
            return json.loads(stripped)
        except json.JSONDecodeError:
            return text_input
    return text_input


def _update_output_text(data: Any) -> str:
    """Extract user-facing output from LangGraph update payloads.

    LangGraph updates can contain internal node state such as routing decisions,
    tool outputs, and classifier payloads. Generic recursive extraction is too
    broad for updates such as ``{"classify": {"route": "x"}}``; only explicit
    output-like fields are treated as user-facing text.
    """
    if not isinstance(data, dict):
        return chunk_to_text(data)

    for key in _OUTPUT_FIELD_KEYS:
        if key in data:
            text = chunk_to_text(data[key])
            if text:
                return text

    latest = ""
    for value in data.values():
        if not isinstance(value, dict):
            continue
        for key in _OUTPUT_FIELD_KEYS:
            if key in value:
                text = chunk_to_text(value[key])
                if text:
                    latest = text
    return latest


class LangGraphAgentkitBridge(BaseAgent):
    """Adapt a compiled LangGraph graph to AgentKit's ADK runtime boundary."""

    _graph: Any = PrivateAttr()
    _graph_factory: bool = PrivateAttr(default=False)
    _input_key: str | None = PrivateAttr(default=None)
    _stream_nodes: frozenset[str] = PrivateAttr(default_factory=frozenset)

    def __init__(
        self,
        graph: Any,
        *,
        name: str = "langgraph_agent",
        description: str = "LangGraph agent adapted for AgentKit runtime",
        input_key: str | None = None,
        stream_nodes: Iterable[str] | str | None = None,
        graph_factory: bool = False,
    ) -> None:
        super().__init__(name=name, description=description)
        self._graph = graph
        self._graph_factory = graph_factory
        self._input_key = input_key
        if isinstance(stream_nodes, str):
            nodes = (stream_nodes,)
        else:
            nodes = tuple(stream_nodes or ())
        self._stream_nodes = frozenset(node for node in nodes if node)

    def _input_payload(self, text_input: str) -> dict[str, Any]:
        if self._input_key:
            return {self._input_key: text_input}
        return {"messages": [HumanMessage(content=text_input)]}

    def _graph_config(self, ctx: InvocationContext) -> dict[str, Any] | None:
        session = getattr(ctx, "session", None)
        session_id = getattr(session, "id", None)
        if not session_id:
            return None
        app_name = getattr(session, "app_name", None)
        user_id = getattr(session, "user_id", None)
        if app_name and user_id:
            raw_identity = f"{app_name}\0{user_id}\0{session_id}"
            digest = hashlib.sha256(raw_identity.encode("utf-8")).hexdigest()
            thread_id = f"agentkit:{digest}"
        else:
            thread_id = session_id
        return {"configurable": {"thread_id": thread_id}}

    async def _graph_for_run(self, config: dict[str, Any] | None) -> Any:
        if not self._graph_factory:
            return self._graph
        call = _factory_call(self._graph, config)
        graph = self._graph(*call.args, **call.kwargs)
        if inspect.isawaitable(graph):
            graph = await graph
        return graph

    def _pending_interrupt(self, ctx: InvocationContext) -> Any | None:
        session = getattr(ctx, "session", None)
        state = getattr(session, "state", None)
        if not isinstance(state, dict):
            return None
        pending = state.get(LANGGRAPH_PENDING_INTERRUPT_STATE_KEY)
        if not pending:
            return None
        if isinstance(pending, dict) and pending.get("agent") not in {None, self.name}:
            return None
        return pending

    def _run_payload(self, ctx: InvocationContext) -> Any:
        text_input = user_text(ctx)
        if self._pending_interrupt(ctx) is None:
            return self._input_payload(text_input)
        if Command is None:
            raise UnsupportedFrameworkAgentError(
                "LangGraph HITL resume requires langgraph.types.Command. "
                "Upgrade langgraph or start a new AgentKit session."
            )
        return Command(resume=_resume_value(text_input))

    def _interrupt_state_delta(self, ctx: InvocationContext, config: dict[str, Any] | None, interrupt: Any) -> dict[str, Any]:
        session = getattr(ctx, "session", None)
        session_id = getattr(session, "id", None)
        if not session_id:
            return {}
        return {
            LANGGRAPH_PENDING_INTERRUPT_STATE_KEY: {
                "agent": self.name,
                "thread_id": config.get("configurable", {}).get("thread_id") if config else session_id,
                "interrupts": interrupt,
            }
        }

    def _final_event(self, ctx: InvocationContext, text: str, *, clear_pending_interrupt: bool) -> Event:
        event_kwargs: dict[str, Any] = {}
        if clear_pending_interrupt:
            event_kwargs["actions"] = EventActions(state_delta={LANGGRAPH_PENDING_INTERRUPT_STATE_KEY: None})
        return Event(
            invocation_id=ctx.invocation_id,
            author=self.name,
            branch=ctx.branch,
            partial=False,
            content=types.Content(role="model", parts=[types.Part(text=text)]),
            **event_kwargs,
        )

    def _clear_pending_interrupt_event(self, ctx: InvocationContext) -> Event:
        return Event(
            invocation_id=ctx.invocation_id,
            author=self.name,
            branch=ctx.branch,
            actions=EventActions(state_delta={LANGGRAPH_PENDING_INTERRUPT_STATE_KEY: None}),
        )

    async def _call_once(self, graph: Any, payload: Any, config: dict[str, Any] | None) -> Any:
        ainvoke = getattr(graph, "ainvoke", None)
        if callable(ainvoke):
            return await ainvoke(payload, **_method_kwargs(ainvoke, {"config": config}))

        invoke = getattr(graph, "invoke", None)
        if callable(invoke):
            return invoke(payload, **_method_kwargs(invoke, {"config": config}))

        raise UnsupportedFrameworkAgentError(
            "LangGraph entry must be a compiled graph-like object exposing "
            "astream, stream, ainvoke, or invoke."
        )

    def _stream_mode(self) -> str | list[str]:
        if self._stream_nodes:
            return ["messages", "updates"]
        return "updates"

    def _sync_stream(self, graph: Any, payload: Any, config: dict[str, Any] | None):
        stream_fn = getattr(graph, "stream", None)
        if not callable(stream_fn):
            return None
        stream_mode = self._stream_mode()
        attempts = [
            {
                "config": config,
                "stream_mode": stream_mode,
                "version": "v2",
            },
            {
                "config": config,
                "stream_mode": stream_mode,
            },
            {"config": config},
        ]

        def iterate_attempts():
            last_error: TypeError | None = None
            for kwargs in attempts:
                emitted = False
                try:
                    stream = stream_fn(payload, **_method_kwargs(stream_fn, kwargs))
                    for item in stream:
                        emitted = True
                        yield item
                    return
                except TypeError as exc:
                    if emitted:
                        raise
                    last_error = exc
            if last_error is not None:
                raise last_error

        return iterate_attempts()

    async def _stream_graph(self, graph: Any, payload: Any, config: dict[str, Any] | None, *, prefer_sync: bool = False):
        if prefer_sync:
            stream = self._sync_stream(graph, payload, config)
            if stream is not None:
                for item in stream:
                    yield item
                return

        astream = getattr(graph, "astream", None)
        if callable(astream):
            stream_mode = self._stream_mode()
            attempts = [
                {
                    "config": config,
                    "stream_mode": stream_mode,
                    "version": "v2",
                },
                {
                    "config": config,
                    "stream_mode": stream_mode,
                },
                {"config": config},
            ]
            last_error: TypeError | None = None
            for kwargs in attempts:
                emitted = False
                try:
                    stream = astream(payload, **_method_kwargs(astream, kwargs))
                    async for item in stream:
                        emitted = True
                        yield item
                    return
                except TypeError as exc:
                    if emitted:
                        raise
                    last_error = exc
            if last_error is not None:
                raise last_error

        stream = self._sync_stream(graph, payload, config)
        if stream is not None:
            for item in stream:
                yield item

    def _message_stream_allowed(self, data: Any) -> bool:
        if not self._stream_nodes:
            return False
        metadata = None
        if isinstance(data, tuple) and len(data) > 1:
            metadata = data[1]
        elif isinstance(data, dict):
            metadata = data.get("metadata")
        if not isinstance(metadata, dict):
            return False
        node = metadata.get("langgraph_node")
        return isinstance(node, str) and node in self._stream_nodes

    async def _run_async_impl(
        self,
        ctx: InvocationContext,
    ) -> AsyncGenerator[Event, None]:
        config = self._graph_config(ctx)
        resume_pending = self._pending_interrupt(ctx) is not None
        payload = self._run_payload(ctx)
        graph = await self._graph_for_run(config)
        accumulated_text = ""
        last_update: Any = None
        pending_update_text = ""
        streamed = False

        async for item in self._stream_graph(graph, payload, config, prefer_sync=resume_pending):
            streamed = True
            mode = ""
            data = item
            if isinstance(item, tuple) and len(item) == 2 and isinstance(item[0], str):
                mode, data = item
            elif isinstance(item, dict) and isinstance(item.get("type"), str):
                mode = item["type"]
                data = item.get("data")
            elif isinstance(item, dict):
                mode = "updates"

            if mode == "messages":
                if not self._message_stream_allowed(data):
                    continue
                message = data[0] if isinstance(data, tuple) and data else data
                text = chunk_to_text(message)
                if not text:
                    continue
                delta = chunk_delta(accumulated_text, text)
                if not delta:
                    continue
                accumulated_text += delta
                yield adk_event(ctx, self.name, delta, partial=True)
                continue

            if mode == "updates":
                interrupt = _interrupt_payload(data)
                if interrupt is not None:
                    state_delta = self._interrupt_state_delta(ctx, config, interrupt)
                    event_kwargs: dict[str, Any] = {}
                    if state_delta:
                        event_kwargs["actions"] = EventActions(state_delta=state_delta)
                    yield Event(
                        invocation_id=ctx.invocation_id,
                        author=self.name,
                        branch=ctx.branch,
                        interrupted=True,
                        error_code="LANGGRAPH_INTERRUPT",
                        error_message="LangGraph execution interrupted and requires resume input.",
                        custom_metadata={"langgraph_interrupt": interrupt},
                        **event_kwargs,
                    )
                    return
                last_update = data
                text = _update_output_text(data)
                if text:
                    pending_update_text = text
                continue

            text = chunk_to_text(data)
            if text:
                pending_update_text = text

        if streamed:
            update_text = pending_update_text or _update_output_text(last_update)
            final_text = update_text or accumulated_text
        else:
            final_text = _update_output_text(await self._call_once(graph, payload, config))

        if final_text:
            yield self._final_event(ctx, final_text, clear_pending_interrupt=resume_pending)
        elif resume_pending:
            yield self._clear_pending_interrupt_event(ctx)
